
 
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
//import Cadastro.ClienteDAO;
import BancoDados.ConexaoCliente;
import Dao.ClienteDAO;
import Negocio.Cliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ediane
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCep = new javax.swing.JLabel();
        jLSexo = new javax.swing.JLabel();
        jTFCep = new javax.swing.JTextField();
        jLBairro = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jTCPF = new javax.swing.JTextField();
        jTFBairro = new javax.swing.JTextField();
        jLRua = new javax.swing.JLabel();
        javax.swing.JRadioButton jRadioButtonFeminino = new javax.swing.JRadioButton();
        jTFRua = new javax.swing.JTextField();
        JTID = new javax.swing.JTextField();
        jLCidade = new javax.swing.JLabel();
        jLCpf = new javax.swing.JLabel();
        JTNome = new javax.swing.JTextField();
        JLNome = new javax.swing.JLabel();
        ListaCidade = new javax.swing.JComboBox();
        jLEstado = new javax.swing.JLabel();
        jTFCidade = new javax.swing.JTextField();
        jLEmail = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLIdentidade = new javax.swing.JLabel();
        jTFIdentidade = new javax.swing.JTextField();
        jLProfissao = new javax.swing.JLabel();
        jTFProfissao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtGravar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLTelefone = new javax.swing.JLabel();
        jTFTelefone = new javax.swing.JTextField();
        jLCelular = new javax.swing.JLabel();
        jTFCelular = new javax.swing.JTextField();
        jLcodigoCliente = new javax.swing.JLabel();
        jTFDataNascimento = new javax.swing.JTextField();
        jLDataNascimento = new javax.swing.JLabel();
        jLabelCastradoPor = new javax.swing.JLabel();
        jTFCadastradoPor = new javax.swing.JTextField();
        jTFFaixadeDesconto = new javax.swing.JTextField();
        jTFDataCadastro = new javax.swing.JTextField();
        jLFaixaDesconto = new javax.swing.JLabel();
        jLDataCadastro = new javax.swing.JLabel();
        jBIncluir = new javax.swing.JButton();
        jAlterar = new javax.swing.JButton();
        jBtPesquisar = new javax.swing.JButton();
        jBtImprimir = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBPrimeiro = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPObservacao = new javax.swing.JTextPane();
        jLObservacaoCliente = new javax.swing.JLabel();
        jBLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCep.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCep.setText("CEP:");
        getContentPane().add(jLCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 215, -1, -1));

        jLSexo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSexo.setText("Sexo:");
        getContentPane().add(jLSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 111, 76, 20));

        jTFCep.setMaximumSize(null);
        getContentPane().add(jTFCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 235, 103, -1));

        jLBairro.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLBairro.setText("Bairro");
        getContentPane().add(jLBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 162, -1, -1));

        jRadioButtonMasculino.setSelected(true);
        jRadioButtonMasculino.setText("M");
        getContentPane().add(jRadioButtonMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 133, -1, -1));

        jTCPF.setMaximumSize(null);
        jTCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 306, 163, -1));

        jTFBairro.setMaximumSize(null);
        getContentPane().add(jTFBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 182, 387, -1));

        jLRua.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLRua.setText("Endereço ");
        getContentPane().add(jLRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 162, -1, -1));

        jRadioButtonFeminino.setSelected(true);
        jRadioButtonFeminino.setText("F");
        getContentPane().add(jRadioButtonFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 133, -1, -1));

        jTFRua.setMaximumSize(null);
        jTFRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRuaActionPerformed(evt);
            }
        });
        getContentPane().add(jTFRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 182, 218, 22));

        JTID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTID.setMaximumSize(null);
        JTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTIDActionPerformed(evt);
            }
        });
        getContentPane().add(JTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 131, 65, 25));

        jLCidade.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCidade.setText("Cidade");
        getContentPane().add(jLCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 215, -1, -1));

        jLCpf.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCpf.setText("CPF");
        getContentPane().add(jLCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 286, -1, -1));

        JTNome.setForeground(new java.awt.Color(102, 102, 0));
        JTNome.setMaximumSize(null);
        JTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 131, 472, 25));

        JLNome.setBackground(new java.awt.Color(204, 102, 0));
        JLNome.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        JLNome.setText("Nome ");
        getContentPane().add(JLNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 111, -1, -1));

        ListaCidade.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        ListaCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaCidade.setMaximumSize(null);
        ListaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(ListaCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 235, -1, -1));

        jLEstado.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLEstado.setText("UF");
        getContentPane().add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 220, -1, -1));

        jTFCidade.setMaximumSize(null);
        jTFCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTFCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 235, 142, -1));

        jLEmail.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLEmail.setText("E-mail");
        getContentPane().add(jLEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 215, -1, -1));

        jTFEmail.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jTFEmail.setMaximumSize(null);
        getContentPane().add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 235, 281, -1));

        jLIdentidade.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLIdentidade.setText("Identidade");
        getContentPane().add(jLIdentidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 286, -1, -1));

        jTFIdentidade.setMaximumSize(null);
        getContentPane().add(jTFIdentidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 306, 124, -1));

        jLProfissao.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLProfissao.setText("Profissão");
        getContentPane().add(jLProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 286, -1, -1));

        jTFProfissao.setMaximumSize(null);
        getContentPane().add(jTFProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 306, 199, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 333, -1, -1));

        jBtGravar.setBackground(new java.awt.Color(0, 102, 0));
        jBtGravar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jBtGravar.setForeground(new java.awt.Color(0, 153, 0));
        jBtGravar.setText("Gravar");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 409, 85, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 409, -1, -1));

        jLTelefone.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLTelefone.setText("Telefone");
        getContentPane().add(jLTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 337, -1, -1));

        jTFTelefone.setMaximumSize(null);
        getContentPane().add(jTFTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 357, 164, -1));

        jLCelular.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLCelular.setText("Celular");
        getContentPane().add(jLCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 337, -1, -1));

        jTFCelular.setMaximumSize(null);
        jTFCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCelularActionPerformed(evt);
            }
        });
        getContentPane().add(jTFCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 357, 123, -1));

        jLcodigoCliente.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLcodigoCliente.setText("Código");
        getContentPane().add(jLcodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 111, -1, -1));

        jTFDataNascimento.setMaximumSize(null);
        jTFDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDataNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jTFDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 306, 98, -1));

        jLDataNascimento.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLDataNascimento.setText("Data Nascimento");
        getContentPane().add(jLDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 286, -1, -1));

        jLabelCastradoPor.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabelCastradoPor.setText("Cadastrado Por");
        getContentPane().add(jLabelCastradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 60, 107, -1));

        jTFCadastradoPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCadastradoPorActionPerformed(evt);
            }
        });
        getContentPane().add(jTFCadastradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 80, 156, -1));

        jTFFaixadeDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFFaixadeDescontoActionPerformed(evt);
            }
        });
        getContentPane().add(jTFFaixadeDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 80, 100, -1));
        getContentPane().add(jTFDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 80, 114, -1));

        jLFaixaDesconto.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLFaixaDesconto.setText("Faixa de Desconto");
        getContentPane().add(jLFaixaDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 60, -1, -1));

        jLDataCadastro.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLDataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDataCadastro.setText("Data Cadastro");
        getContentPane().add(jLDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 59, 114, 0));

        jBIncluir.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBIncluir.setText("Incluir");
        getContentPane().add(jBIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 11, 87, 31));

        jAlterar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jAlterar.setText("Alterar");
        getContentPane().add(jAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 11, 87, 31));

        jBtPesquisar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBtPesquisar.setText("Pesquisar");
        getContentPane().add(jBtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 11, -1, 31));

        jBtImprimir.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBtImprimir.setText("Imprimir");
        getContentPane().add(jBtImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 11, -1, 31));

        jBtSair.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBtSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 11, 87, 31));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setText("Data Cadastro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 60, -1, -1));

        jBPrimeiro.setText("|<");
        getContentPane().add(jBPrimeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 15, -1, -1));

        jBProximo.setText(">");
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });
        getContentPane().add(jBProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 15, 45, -1));

        jBUltimo.setText(">|");
        getContentPane().add(jBUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 15, -1, -1));

        jBAnterior.setText("<");
        getContentPane().add(jBAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 15, 45, -1));

        jScrollPane1.setViewportView(jTPObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 70, 226, 307));

        jLObservacaoCliente.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLObservacaoCliente.setText("Observações");
        getContentPane().add(jLObservacaoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 383, -1, -1));

        jBLimpar.setBackground(new java.awt.Color(255, 51, 51));
        jBLimpar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jBLimpar.setForeground(new java.awt.Color(153, 0, 0));
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 409, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCPFActionPerformed

    private void jTFRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFRuaActionPerformed

    private void JTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNomeActionPerformed

    private void ListaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaCidadeActionPerformed

    private void jTFCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCidadeActionPerformed

    private void jTFCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCelularActionPerformed

    private void jTFDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDataNascimentoActionPerformed

    private void jTFCadastradoPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCadastradoPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCadastradoPorActionPerformed

    private void jTFFaixadeDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFFaixadeDescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFFaixadeDescontoActionPerformed

    private void JTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        // TODO add your handling code here:
   JTNome.setText("");
   jTCPF.setText("");
   jTFBairro.setText("");
   jTFCadastradoPor.setText("");
   jTFCelular.setText("");
   jTFCep.setText("");
   jTFCidade.setText("");       
   jTFDataCadastro.setText("");       
   jTFDataNascimento.setText("");   
   jTFEmail.setText("");
   jTFIdentidade.setText("");
   jTFFaixadeDesconto.setText("");
   jTFProfissao.setText("");
   jTFRua.setText("");
   jTFTelefone.setText("");
   jTPObservacao.setText("");
                  
    }//GEN-LAST:event_jBLimparActionPerformed
//cadastrando cliente
    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        // instanciando objeto cliente e adicionando valores aos atributos
     
      if (verificaDados()){
            cadastro();
            desabilitaDados();
        }
                                             
      //fecha else
    }//GEN-LAST:event_jBtGravarActionPerformed
  public void cadastro(){
        try {
        Cliente c1 = new Cliente();
        
        c1.setCPF(jTCPF.getText());
        c1.setNome(JTNome.getText());
        
            ClienteDAO cd = new ClienteDAO();
            cd.adiciona(c1);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  //nao permite deixar campos em branco 
  public boolean verificaDados(){
        if(!jTCPF.getText().equals("")&&!JTNome.getText().equals("")){
            return true;
        }
        else{
            JOptionPane.showMessageDialog(null,"Campos obrigatórios em branco!");
            return false;
        }
    }
   public void desabilitaDados(){
        jTCPF.setEditable(false);
        JTNome.setEditable(false);
       // jTFcapacidade.setEditable(false);
    }
    
    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLNome;
    private javax.swing.JTextField JTID;
    private javax.swing.JTextField JTNome;
    private javax.swing.JComboBox ListaCidade;
    private javax.swing.JButton jAlterar;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPrimeiro;
    private javax.swing.JButton jBProximo;
    private javax.swing.JButton jBUltimo;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtImprimir;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLCpf;
    private javax.swing.JLabel jLDataCadastro;
    private javax.swing.JLabel jLDataNascimento;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLFaixaDesconto;
    private javax.swing.JLabel jLIdentidade;
    private javax.swing.JLabel jLObservacaoCliente;
    private javax.swing.JLabel jLProfissao;
    private javax.swing.JLabel jLRua;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCastradoPor;
    private javax.swing.JLabel jLcodigoCliente;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTFBairro;
    private javax.swing.JTextField jTFCadastradoPor;
    private javax.swing.JTextField jTFCelular;
    private javax.swing.JTextField jTFCep;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFDataCadastro;
    private javax.swing.JTextField jTFDataNascimento;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFFaixadeDesconto;
    private javax.swing.JTextField jTFIdentidade;
    private javax.swing.JTextField jTFProfissao;
    private javax.swing.JTextField jTFRua;
    private javax.swing.JTextField jTFTelefone;
    private javax.swing.JTextPane jTPObservacao;
    // End of variables declaration//GEN-END:variables
}
