/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JDesktopPane;


/**
 *
 * @author RAFAELA
 */
public class JFTelaInicial extends javax.swing.JFrame {
    
    private static JFTelaInicial p;
    
    //método padrão Singleton, garante que irá gerar uma única instância da tela inicial
    public static JFTelaInicial getInstancia(){
    
        if(p == null){
            p = new JFTelaInicial();
        }
        return p;
    }
    
    //método que adiciona o jdesktopPane a instancia gerada da tela inicial
    public static JDesktopPane getDPane(){
        return getInstancia().jdPane;
    }

    /**
     * Creates new form JFTelaInicial
     */
    public JFTelaInicial() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPane = new javax.swing.JDesktopPane();
        jmPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemServico = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemVeiculo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SYSTUR - Sistema de Agência de Turismo");

        jMenuCadastro.setText("Cadastros");
        jMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroActionPerformed(evt);
            }
        });

        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemClientes);

        jMenuItemServico.setText("Serviços Turísticos");
        jMenuItemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemServico);

        jMenuItemFuncionario.setText("Funcionários");
        jMenuCadastro.add(jMenuItemFuncionario);

        jMenuItemVeiculo.setText("Veículos");
        jMenuItemVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemVeiculoMouseClicked(evt);
            }
        });
        jMenuItemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeiculoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemVeiculo);
        jMenuCadastro.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemSair);

        jmPrincipal.add(jMenuCadastro);

        jMenuVenda.setText("Vendas");
        jMenuVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVendaMouseClicked(evt);
            }
        });
        jMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendaActionPerformed(evt);
            }
        });
        jmPrincipal.add(jMenuVenda);

        jMenuRelatorio.setText("Relatórios");
        jmPrincipal.add(jMenuRelatorio);

        jMenuAjuda.setText("Ajuda");
        jmPrincipal.add(jMenuAjuda);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jmPrincipal.add(jMenuSair);

        setJMenuBar(jmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdPane, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdPane, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoMouseClicked
        // TODO add your handling code here:
        //TelaVeiculo tv = new TelaVeiculo(this,true);  
        //tv.setVisible(true);  

    }//GEN-LAST:event_jMenuItemVeiculoMouseClicked

    private void jMenuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoActionPerformed
        // TODO add your handling code here:
       criaJanelaCadVeiculo();
    }//GEN-LAST:event_jMenuItemVeiculoActionPerformed

    private void jMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuCadastroActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        // TODO add your handling code here:
        criaJanelaCadCliente ();
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServicoActionPerformed
        // TODO add your handling code here:
        criaJanelaCadServico();
    }//GEN-LAST:event_jMenuItemServicoActionPerformed

    private void jMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendaActionPerformed
        // TODO add your handling code here:
        criaJanelaVenda();
    }//GEN-LAST:event_jMenuVendaActionPerformed

    private void jMenuVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVendaMouseClicked
        // TODO add your handling code here:
        criaJanelaVenda();
    }//GEN-LAST:event_jMenuVendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                getInstancia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemServico;
    private javax.swing.JMenuItem jMenuItemVeiculo;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane jdPane;
    private javax.swing.JMenuBar jmPrincipal;
    // End of variables declaration//GEN-END:variables

   //Criando metodo para chamar internal frame dos cadastros
    jifCadVeiculo cadveiculo;
    JifCadastroClientes cadCliente;
    jifCadServico cadServico;
    jifVenda venda;
    jifServico servico;
    
    private void criaJanelaCadVeiculo() {
        if(cadveiculo==null){
            cadveiculo = new jifCadVeiculo();
        }
        
        jdPane.add(cadveiculo);
        cadveiculo.setVisible(true);
    }

  private void criaJanelaCadCliente (){ 
          if(cadCliente ==null){
            cadCliente = new JifCadastroClientes();
        }
        
        jdPane.add(cadCliente);
        cadCliente.setVisible(true);
    }
  
  private void criaJanelaCadServico (){ 
          if(servico == null){
            servico = new jifServico();
        }
        
        jdPane.add(servico);
        servico.setVisible(true);
    }
  
  private void criaJanelaVenda (){ 
          if(venda ==null){
            venda = new jifVenda();
        }
        
        jdPane.add(venda);
        venda.setVisible(true);
    }
    
    
    
    
}
