/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//import Dao.ServicoDao;
//import Dao.VeiculoDao;
import DAO.ServicoDao;
import Negocio.ServicoTuristico;
import Negocio.Veiculo;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELA
 */
public class jifCadServico extends javax.swing.JInternalFrame {

    DefaultTableModel tmServico = new DefaultTableModel(null, new String[]{"IdServiço", "Valor", "Nome", "Descrição",
                "Lotação Máxima", "Lotação Mínima", "Observacao"});
    List<ServicoTuristico> servico;
    ListSelectionModel lsmServico;

    /**
     * Creates new form jifCadServico
     */
    public jifCadServico() {
        initComponents();
        desabilitaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelOpcoes = new javax.swing.JPanel();
        jtfPesquisaServico = new javax.swing.JTextField();
        jbtPesquisaServico = new javax.swing.JButton();
        jPanelCadastro = new javax.swing.JPanel();
        jlbIdServico = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jlbDescricao = new javax.swing.JLabel();
        jlbLotMax = new javax.swing.JLabel();
        jlbLotMin = new javax.swing.JLabel();
        jtfIdServico = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfDescricao = new javax.swing.JTextField();
        jtfLotMax = new javax.swing.JTextField();
        jtfLotMin = new javax.swing.JTextField();
        jlbObs = new javax.swing.JLabel();
        jtfObs = new javax.swing.JTextField();
        jbtGravar = new javax.swing.JButton();
        jbtAlterar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtNovo = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jScrollPanePesquisa = new javax.swing.JScrollPane();
        jTabPesquisa = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();

        setTitle("Cadastro de Serviços Turísticos");

        jPanelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jtfPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaServicoActionPerformed(evt);
            }
        });

        jbtPesquisaServico.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\procurar.png")); // NOI18N
        jbtPesquisaServico.setText("Pesquisar");
        jbtPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisaServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jtfPesquisaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtPesquisaServico)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesquisaServico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jlbIdServico.setText("IdServiço:");

        jlbValor.setText("Valor:");

        jlbNome.setText("Nome:");

        jlbDescricao.setText("Descrição:");

        jlbLotMax.setText("Lotação Máxima:");

        jlbLotMin.setText("Lotação Mínima:");

        jlbObs.setText("Observação:");

        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });

        jbtAlterar.setText("Alterar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jlbDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbIdServico)
                                    .addComponent(jlbValor)
                                    .addComponent(jlbNome))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIdServico, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jtfValor)
                                    .addComponent(jtfNome))))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbLotMin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbObs))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfLotMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfObs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtNovo)
                                    .addComponent(jlbLotMax))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfLotMax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtGravar)
                        .addGap(30, 30, 30)
                        .addComponent(jbtAlterar)
                        .addGap(37, 37, 37)
                        .addComponent(jbtExcluir)))
                .addGap(23, 23, 23))
        );

        jPanelCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfDescricao, jtfIdServico, jtfLotMax, jtfLotMin, jtfNome, jtfObs, jtfValor});

        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbIdServico)
                    .addComponent(jlbLotMax)
                    .addComponent(jtfIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLotMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValor)
                    .addComponent(jlbLotMin)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLotMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbObs)
                    .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDescricao)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtGravar)
                    .addComponent(jbtAlterar)
                    .addComponent(jbtExcluir)
                    .addComponent(jbtNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jTabPesquisa.setModel(tmServico);
        jTabPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmServico = jTabPesquisa.getSelectionModel();
        lsmServico.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    linhaSelecionada(jTabPesquisa);
                }
            }
        });
        jScrollPanePesquisa.setViewportView(jTabPesquisa);

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButtonSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\cancelar.png")); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaServicoActionPerformed

    private void jbtPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisaServicoActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            listarServicos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão pesquisar" + ex);
        }
    }//GEN-LAST:event_jbtPesquisaServicoActionPerformed

    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        // TODO add your handling code here:
        if (verificaDados()) {
            cadastro();
            desabilitaDados();
        }
    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            alterar();
            listarServicos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão alterar" + ex);
        }
    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            excluir();
            mostraPesquisa(servico);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão excluir\n" + ex);
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        // TODO add your handling code here:
        habilitaDados();

        jtfIdServico.setText("");
        jtfValor.setText("");
        jtfNome.setText("");
        jtfDescricao.setText("");
        jtfLotMax.setText("");
        jtfLotMin.setText("");
        jtfObs.setText("");
    }//GEN-LAST:event_jbtNovoActionPerformed

    //método para fechar jinternalframe
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPanePesquisa;
    private javax.swing.JTable jTabPesquisa;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisaServico;
    private javax.swing.JLabel jlbDescricao;
    private javax.swing.JLabel jlbIdServico;
    private javax.swing.JLabel jlbLotMax;
    private javax.swing.JLabel jlbLotMin;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbObs;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfIdServico;
    private javax.swing.JTextField jtfLotMax;
    private javax.swing.JTextField jtfLotMin;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfObs;
    private javax.swing.JTextField jtfPesquisaServico;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
    //realiza uma pesquisa

    public void listarServicos() throws SQLException {
        ServicoDao dao = new ServicoDao();
        servico = dao.getLista("%" + jtfPesquisaServico.getText() + "%");
        mostraPesquisa(servico);
    }

    //cadastra novo veiculo
    public void cadastro() {
        try {
            ServicoTuristico v = new ServicoTuristico();

            v.setValor(Double.parseDouble(jtfValor.getText()));
            v.setNome(jtfNome.getText());
            v.setDescricao(jtfDescricao.getText());
            v.setLotMax(Integer.parseInt(jtfLotMax.getText()));
            v.setLotMin(Integer.parseInt(jtfLotMin.getText()));
            v.setObs(jtfObs.getText());

            ServicoDao vd = new ServicoDao();
            vd.adiciona(v);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            //JOptionPane.showMessageDialog(null, "Erro no botão cadastrar\n" + ex);
        }
    }

    public void excluir() throws SQLException {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir os dados? ",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_NO_OPTION) {
            ServicoDao dao = new ServicoDao();
            dao.exclui(servico.get(jTabPesquisa.getSelectedRow()));
            mostraPesquisa(servico);
        }
    }
    //desabilita a ediçao dos dados

    public void desabilitaDados() {
        jtfIdServico.setEditable(false);
        jtfValor.setEditable(false);
        jtfNome.setEditable(false);
        jtfDescricao.setEditable(false);
        jtfLotMax.setEditable(false);
        jtfLotMin.setEditable(false);
        jtfObs.setEditable(false);

    }
    //permite a ediçao dos dados

    public void habilitaDados() {
        jtfIdServico.setEditable(false);
        jtfValor.setEditable(true);
        jtfNome.setEditable(true);
        jtfDescricao.setEditable(true);
        jtfLotMax.setEditable(true);
        jtfLotMin.setEditable(true);
        jtfObs.setEditable(true);
    }

    /**
     * @param args the command line arguments
     */
    //seleciona uma linha na tabela para alterar ou excluir dados 
    private void linhaSelecionada(JTable tabela) {
        if (jTabPesquisa.getSelectedRow() != -1) {
            habilitaDados();
            jtfIdServico.setText(String.valueOf(servico.get(tabela.getSelectedRow()).getIdServico()));
            jtfValor.setText(String.valueOf(servico.get(tabela.getSelectedRow()).getValor()));
            jtfNome.setText(servico.get(tabela.getSelectedRow()).getNome());
            jtfDescricao.setText(servico.get(tabela.getSelectedRow()).getDescricao());
            jtfLotMax.setText(String.valueOf(servico.get(tabela.getSelectedRow()).getLotMax()));
            jtfLotMin.setText(String.valueOf(servico.get(tabela.getSelectedRow()).getLotMin()));
            jtfObs.setText(servico.get(tabela.getSelectedRow()).getObs());
        } else {

            jtfIdServico.setText("");
            jtfValor.setText("");
            jtfNome.setText("");
            jtfDescricao.setText("");
            jtfLotMax.setText("");
            jtfLotMin.setText("");
            jtfObs.setText("");
        }
    }

    //verifica se foi deixado algum campo obrigatório em branco
    public boolean verificaDados() {
        if ((!jtfValor.getText().equals("")) && (!jtfNome.getText().equals(""))
                && (!jtfDescricao.getText().equals("")) && (!jtfLotMax.getText().equals(""))
                && (!jtfLotMin.getText().equals(""))) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios em branco!");
            return false;
        }
    }

    //mostra a pesquisa na tabela
    private void mostraPesquisa(List<ServicoTuristico> servico) {

        while (tmServico.getRowCount() > 0) {
            tmServico.removeRow(0);
        }
        if (servico.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum veículo cadastrado!");
        } else {
            String[] linha = new String[]{null, null, null, null, null, null, null};
            for (int i = 0; i < servico.size(); i++) {

                tmServico.addRow(linha);
                tmServico.setValueAt(servico.get(i).getIdServico(), i, 0);
                tmServico.setValueAt(servico.get(i).getValor(), i, 1);
                tmServico.setValueAt(servico.get(i).getNome(), i, 2);
                tmServico.setValueAt(servico.get(i).getDescricao(), i, 3);
                tmServico.setValueAt(servico.get(i).getLotMax(), i, 4);
                tmServico.setValueAt(servico.get(i).getLotMin(), i, 5);
                tmServico.setValueAt(servico.get(i).getObs(), i, 6);

            }
        }
    }

    //altera os dados selecionados na tabela
    private void alterar() throws SQLException {
        if (jTabPesquisa.getSelectedRow() != -1) {
            if (verificaDados()) {
                ServicoTuristico v1 = new ServicoTuristico();
                ServicoDao dao = new ServicoDao();
                v1.setIdServico(Integer.valueOf(jtfIdServico.getText()));
                v1.setValor(Double.valueOf(jtfValor.getText()));
                v1.setNome(jtfNome.getText());
                v1.setDescricao(jtfDescricao.getText());
                v1.setLotMax(Integer.parseInt(jtfLotMax.getText()));
                v1.setObs(jtfObs.getText());
                dao.altera(v1);
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
            }
        }
    }
}
