/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.ServicoController;
import DAO.ServicoDao;
import Negocio.ServicoTuristico;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELA
 */
public class jifServico extends javax.swing.JInternalFrame {
    
    DefaultTableModel tmServico = new DefaultTableModel(null, new String[]{"IdServiço", "Valor", "Nome", "Descrição",
                "Lotação Máxima", "Lotação Mínima", "Observacao"});
    private List<ServicoTuristico> servicoList;
    ListSelectionModel lsmServico;

    /**
     * Creates new form jifServico
     */
    public jifServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalServico = new javax.swing.JPanel();
        jPanelOpcoes = new javax.swing.JPanel();
        jtfPesquisaServico = new javax.swing.JTextField();
        jbtPesquisaServico = new javax.swing.JButton();
        jPanelCadastroServico = new javax.swing.JPanel();
        jlbIdServico = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jlbDescricao = new javax.swing.JLabel();
        jlbLotMax = new javax.swing.JLabel();
        jlbLotMin = new javax.swing.JLabel();
        jtfIdServico = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfDescricao = new javax.swing.JTextField();
        jtfLotMax = new javax.swing.JTextField();
        jtfLotMin = new javax.swing.JTextField();
        jlbObs = new javax.swing.JLabel();
        jtfObs = new javax.swing.JTextField();
        jbtGravar = new javax.swing.JButton();
        jbtAlterar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtNovo = new javax.swing.JButton();
        jPanelPesquisa = new javax.swing.JPanel();
        jScrollPanePesquisa = new javax.swing.JScrollPane();
        jTabPesquisa = new javax.swing.JTable();

        jPanelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jtfPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaServicoActionPerformed(evt);
            }
        });

        jbtPesquisaServico.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\procurar.png")); // NOI18N
        jbtPesquisaServico.setText("Pesquisar");
        jbtPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisaServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jtfPesquisaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtPesquisaServico)
                .addGap(0, 153, Short.MAX_VALUE))
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisaServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesquisaServico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCadastroServico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jlbIdServico.setText("IdServiço:");

        jlbValor.setText("Valor:");

        jlbNome.setText("Nome:");

        jlbDescricao.setText("Descrição:");

        jlbLotMax.setText("Lotação Máxima:");

        jlbLotMin.setText("Lotação Mínima:");

        jlbObs.setText("Observação:");

        jbtGravar.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\ok.png")); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });

        jbtAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\edit.png")); // NOI18N
        jbtAlterar.setText("Alterar");
        jbtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAlterarActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\cancelar.png")); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtNovo.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAFAELA\\Downloads\\MiniCurso\\imgs\\editcopy.png")); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroServicoLayout = new javax.swing.GroupLayout(jPanelCadastroServico);
        jPanelCadastroServico.setLayout(jPanelCadastroServicoLayout);
        jPanelCadastroServicoLayout.setHorizontalGroup(
            jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addComponent(jlbDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbIdServico)
                                    .addComponent(jlbValor)
                                    .addComponent(jlbNome))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIdServico, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jtfValor)
                                    .addComponent(jtfNome))))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addComponent(jlbLotMax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfLotMax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbLotMin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbObs))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtNovo)
                                    .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfLotMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfObs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtGravar)
                        .addGap(30, 30, 30)
                        .addComponent(jbtAlterar)
                        .addGap(37, 37, 37)
                        .addComponent(jbtExcluir)))
                .addGap(23, 23, 23))
        );
        jPanelCadastroServicoLayout.setVerticalGroup(
            jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbIdServico)
                    .addComponent(jlbLotMax)
                    .addComponent(jtfIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLotMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValor)
                    .addComponent(jlbLotMin)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLotMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbObs)
                    .addComponent(jtfObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDescricao)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtGravar)
                    .addComponent(jbtAlterar)
                    .addComponent(jbtExcluir)
                    .addComponent(jbtNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jTabPesquisa.setModel(tmServico);
        jTabPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmServico = jTabPesquisa.getSelectionModel();
        lsmServico.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    linhaSelecionada(jTabPesquisa);
                }
            }
        });
        jScrollPanePesquisa.setViewportView(jTabPesquisa);

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPanePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPanePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanelPrincipalServicoLayout = new javax.swing.GroupLayout(jPanelPrincipalServico);
        jPanelPrincipalServico.setLayout(jPanelPrincipalServicoLayout);
        jPanelPrincipalServicoLayout.setHorizontalGroup(
            jPanelPrincipalServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCadastroServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrincipalServicoLayout.setVerticalGroup(
            jPanelPrincipalServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalServicoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCadastroServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipalServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanelPrincipalServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        try {
            // TODO add your handling code here:
            onClickGravar();
        } catch (SQLException ex) {
            Logger.getLogger(jifServico.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jbtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAlterarActionPerformed

            // TODO add your handling code here:
            onClickAlterar();
            listarServicos();
            //mostraPesquisa(servicoList);

    }//GEN-LAST:event_jbtAlterarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        try {
            // TODO add your handling code here:
            onClickExcluir();
            mostraPesquisa(servicoList);
        } catch (SQLException ex) {
            Logger.getLogger(jifServico.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jtfPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisaServicoActionPerformed

    private void jbtPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisaServicoActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
            listarServicos();

    }//GEN-LAST:event_jbtPesquisaServicoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCadastroServico;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelPrincipalServico;
    private javax.swing.JScrollPane jScrollPanePesquisa;
    private javax.swing.JTable jTabPesquisa;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisaServico;
    private javax.swing.JLabel jlbDescricao;
    private javax.swing.JLabel jlbIdServico;
    private javax.swing.JLabel jlbLotMax;
    private javax.swing.JLabel jlbLotMin;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbObs;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfIdServico;
    private javax.swing.JTextField jtfLotMax;
    private javax.swing.JTextField jtfLotMin;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfObs;
    private javax.swing.JTextField jtfPesquisaServico;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables

    private void onClickGravar() throws SQLException {
        ServicoController sc = new ServicoController();
        //Integer.valueOf(jtfIdServico.getText()),
            try {
                sc.salvar(Double.valueOf(jtfValor.getText()), jtfNome.getText(), jtfDescricao.getText(), Integer.valueOf(jtfLotMax.getText())
                        , Integer.valueOf(jtfLotMin.getText()), jtfObs.getText());
                JOptionPane.showMessageDialog(null, "Dados gravados com sucesso!");
                
            } catch (SQLException e){
                
                JOptionPane.showMessageDialog(this, "Não foi possível cadastrar serviço! "+ e.getLocalizedMessage());
            
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Erro no formato dos dados "+ ex.getLocalizedMessage());
               // Logger.getLogger(jifServico.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        
    }

    private void listarServicos() {
        ServicoController sc = new ServicoController();
        servicoList = sc.listaServicos("%" + jtfPesquisaServico.getText() + "%");
        mostraPesquisa(servicoList);
        
    }
    
    //mostra a pesquisa na tabela
    private void mostraPesquisa(List<ServicoTuristico> servicoList) {


        while (tmServico.getRowCount() > 0) {
            tmServico.removeRow(0);
        }
        if (servicoList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum serviço cadastrado!");
        } else {
            String[] linha = new String[]{null, null, null, null, null, null, null};
            for (int i = 0; i < servicoList.size(); i++) {

                tmServico.addRow(linha);
                
                tmServico.setValueAt(servicoList.get(i).getIdServico(), i, 0);
                tmServico.setValueAt(servicoList.get(i).getValor(), i, 1);
                tmServico.setValueAt(servicoList.get(i).getNome(), i, 2);
                tmServico.setValueAt(servicoList.get(i).getDescricao(), i, 3);
                tmServico.setValueAt(servicoList.get(i).getLotMax(), i, 4);
                tmServico.setValueAt(servicoList.get(i).getLotMin(), i, 5);
                tmServico.setValueAt(servicoList.get(i).getObs(), i, 6);

            }
        }
        
    }
    
     private void linhaSelecionada(JTable tabela) {
        if (jTabPesquisa.getSelectedRow() != -1) {
            habilitaDados();
            jtfIdServico.setText(String.valueOf(servicoList.get(tabela.getSelectedRow()).getIdServico()));
            jtfValor.setText(String.valueOf(servicoList.get(tabela.getSelectedRow()).getValor()));
            jtfNome.setText(servicoList.get(tabela.getSelectedRow()).getNome());
            jtfDescricao.setText(servicoList.get(tabela.getSelectedRow()).getDescricao());
            jtfLotMax.setText(String.valueOf(servicoList.get(tabela.getSelectedRow()).getLotMax()));
            jtfLotMin.setText(String.valueOf(servicoList.get(tabela.getSelectedRow()).getLotMin()));
            jtfObs.setText(servicoList.get(tabela.getSelectedRow()).getObs());
        } else {

            jtfIdServico.setText("");
            jtfValor.setText("");
            jtfNome.setText("");
            jtfDescricao.setText("");
            jtfLotMax.setText("");
            jtfLotMin.setText("");
            jtfObs.setText("");
        }
    }
        public void desabilitaDados() {
        jtfIdServico.setEditable(false);
        jtfValor.setEditable(false);
        jtfNome.setEditable(false);
        jtfDescricao.setEditable(false);
        jtfLotMax.setEditable(false);
        jtfLotMin.setEditable(false);
        jtfObs.setEditable(false);

    }
    //permite a ediçao dos dados

    public void habilitaDados() {
        jtfIdServico.setEditable(false);
        jtfValor.setEditable(true);
        jtfNome.setEditable(true);
        jtfDescricao.setEditable(true);
        jtfLotMax.setEditable(true);
        jtfLotMin.setEditable(true);
        jtfObs.setEditable(true);
    }

    private void onClickAlterar(){
        if (jTabPesquisa.getSelectedRow() != -1) {
            if (verificaDados()) {
                
                //ServicoTuristico v1 = new ServicoTuristico();
                ServicoController sc = new ServicoController();
                try {
                    // v1.setIdServico(Integer.valueOf(jtfIdServico.getText()));
                     //v1.setValor(Double.parseDouble(jtfValor.getText()));
                     //v1.setNome(jtfNome.getText());
                    // v1.setDescricao(jtfDescricao.getText());
                     //v1.setLotMax(Integer.parseInt(jtfLotMax.getText()));
                     //v1.setLotMin(Integer.parseInt(jtfLotMin.getText()));
                     //v1.setObs(jtfObs.getText());
                     
                     sc.alterar(Integer.valueOf(jtfIdServico.getText()),Double.valueOf(jtfValor.getText()), jtfNome.getText(), 
                             jtfDescricao.getText(), Integer.valueOf(jtfLotMax.getText())
                             , Integer.valueOf(jtfLotMin.getText()), jtfObs.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(jifServico.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(jifServico.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
            }
        }
    }
    
     //verifica se foi deixado algum campo obrigatório em branco
    public boolean verificaDados() {
        if ((!jtfValor.getText().equals("")) && (!jtfNome.getText().equals(""))
                && (!jtfDescricao.getText().equals("")) && (!jtfLotMax.getText().equals(""))
                && (!jtfLotMin.getText().equals(""))) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios em branco!");
            return false;
        }
    }

    private void onClickExcluir() throws SQLException {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir os dados? ",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_NO_OPTION) {
            //ServicoDao dao = new ServicoDao();
            ServicoController sc = new ServicoController();
            sc.excluir(servicoList.get(jTabPesquisa.getSelectedRow()));
            mostraPesquisa(servicoList);
        }
    }
    }
    

