/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.VeiculoDao;
import Negocio.Veiculo;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELA
 */
public class TelaVeiculo extends javax.swing.JFrame {

    //define o modelo da tabela, suas colunas
    DefaultTableModel tmVeiculo = new DefaultTableModel(null, new String[]{"Placa", "Cor", "Chassi",
                "Modelo", "Marca", "Capacidade", "Status", "Tipo", "Observacao"});
    List<Veiculo> veiculo;
    ListSelectionModel lsmVeiculo;

    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo() {
        initComponents();
        desabilitaDados();
        //listarVeiculos();
    }

    //TelaVeiculo(JFTelaInicial aThis, boolean b) {
        
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtGravar = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtPesquisar = new javax.swing.JButton();
        jBtNovo = new javax.swing.JButton();
        jTFPesquisar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTFcapacidade = new javax.swing.JTextField();
        jLbCapacidade = new javax.swing.JLabel();
        jTFPlaca = new javax.swing.JTextField();
        jLbPlaca = new javax.swing.JLabel();
        jLbChassi = new javax.swing.JLabel();
        jTFChassi = new javax.swing.JTextField();
        jLbCor = new javax.swing.JLabel();
        jTFCor = new javax.swing.JTextField();
        jTFModelo = new javax.swing.JTextField();
        jTFMarca = new javax.swing.JTextField();
        jLbModelo = new javax.swing.JLabel();
        jLbMarca = new javax.swing.JLabel();
        jLbStatus = new javax.swing.JLabel();
        jLbObs = new javax.swing.JLabel();
        jTFStatus = new javax.swing.JTextField();
        jTFObs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFTipo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabPesquisa = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jBtGravar.setText("Gravar");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });

        jBtAlterar.setText("Alterar");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jBtNovo.setText("Novo");
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtGravar)
                        .addGap(49, 49, 49)
                        .addComponent(jBtAlterar)
                        .addGap(51, 51, 51)
                        .addComponent(jBtExcluir)
                        .addGap(39, 39, 39)
                        .addComponent(jBtNovo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtPesquisar)
                    .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtGravar)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtExcluir)
                    .addComponent(jBtNovo))
                .addGap(254, 254, 254))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jTFcapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcapacidadeActionPerformed(evt);
            }
        });

        jLbCapacidade.setText("Capacidade:");

        jLbPlaca.setText("Placa:");

        jLbChassi.setText("Chassi:");

        jLbCor.setText("Cor:");

        jLbModelo.setText("Modelo:");

        jLbMarca.setText("Marca:");

        jLbStatus.setText("Status:");

        jLbObs.setText("Observação:");

        jLabel1.setText("Tipo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbCor)
                    .addComponent(jLbPlaca)
                    .addComponent(jLbCapacidade)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLbModelo)
                        .addComponent(jLbChassi))
                    .addComponent(jLbMarca))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFcapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTFCor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(jLabel1))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jLbStatus))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jTFChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLbObs)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFObs, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTFChassi, jTFCor, jTFMarca, jTFModelo, jTFPlaca, jTFcapacidade});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbPlaca)
                    .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCor)
                    .addComponent(jTFCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbChassi)
                            .addComponent(jTFChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbObs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbModelo)
                            .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbMarca)
                            .addComponent(jTFMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbCapacidade)
                            .addComponent(jTFcapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTFObs))
                .addGap(19, 19, 19))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jTabPesquisa.setModel(tmVeiculo);
        jTabPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmVeiculo = jTabPesquisa.getSelectionModel();
        lsmVeiculo.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    linhaSelecionada(jTabPesquisa);
                }
            }
        });
        jScrollPane1.setViewportView(jTabPesquisa);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFcapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcapacidadeActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        try {
            // TODO add your handling code here:
            excluir();
            mostraPesquisa(veiculo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão excluir\n" + ex);
        }

    }//GEN-LAST:event_jBtExcluirActionPerformed

    //exclui os dados que foram selecionados na tabela de pesquisa
    public void excluir() throws SQLException {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir os dados? ",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_NO_OPTION) {
            VeiculoDao dao = new VeiculoDao();
            dao.exclui(veiculo.get(jTabPesquisa.getSelectedRow()));
            mostraPesquisa(veiculo);
        }

    }

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        // TODO add your handling code here:
        if (verificaDados()) {
            cadastro();
            desabilitaDados();
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    //realiza uma pesquisa
    public void listarVeiculos() throws SQLException {
        VeiculoDao dao = new VeiculoDao();
        veiculo = dao.getLista("%" + jTFPesquisar.getText() + "%");
        mostraPesquisa(veiculo);
    }

    //cadastra novo veiculo
    public void cadastro() {
        try {
            Veiculo v = new Veiculo();

            v.setPlaca(jTFPlaca.getText());
            v.setCor(jTFCor.getText());
            v.setChassi(jTFChassi.getText());
            v.setModelo(jTFModelo.getText());
            v.setMarca(jTFMarca.getText());
            v.setCapacidade(Integer.parseInt(jTFcapacidade.getText()));
            v.setStatus(jTFStatus.getText());
            v.setTipo(jTFTipo.getText());
            v.setObservacao(jTFObs.getText());

            VeiculoDao vd = new VeiculoDao();
            vd.adiciona(v);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage() );
            //JOptionPane.showMessageDialog(null, "Erro no botão cadastrar\n" + ex);
        }
    }

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        try {
            // TODO add your handling code here:
            alterar();
            listarVeiculos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão alterar" + ex);
        }

    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
        // TODO add your handling code here:
        habilitaDados();
        //jTFIdVeiculo.setText("");
        jTFPlaca.setText("");
        jTFCor.setText("");
        jTFChassi.setText("");
        jTFModelo.setText("");
        jTFMarca.setText("");
        jTFcapacidade.setText("");
        jTFStatus.setText("");
        jTFTipo.setText("");
        jTFObs.setText("");
    }//GEN-LAST:event_jBtNovoActionPerformed

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        try {
            // TODO add your handling code here:
            listarVeiculos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão pesquisar" + ex);
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    //desabilita a ediçao dos dados
    public void desabilitaDados() {
        //jTFIdVeiculo.setEditable(false);
        jTFPlaca.setEditable(false);
        jTFCor.setEditable(false);
        jTFChassi.setEditable(false);
        jTFModelo.setEditable(false);
        jTFMarca.setEditable(false);
        jTFcapacidade.setEditable(false);
        jTFStatus.setEditable(false);
        jTFTipo.setEditable(false);
        jTFObs.setEditable(false);
    }
    //permite a ediçao dos dados

    public void habilitaDados() {
        //jTFIdVeiculo.setEditable(false);
        jTFPlaca.setEditable(true);
        jTFCor.setEditable(true);
        jTFChassi.setEditable(true);
        jTFModelo.setEditable(true);
        jTFMarca.setEditable(true);
        jTFcapacidade.setEditable(true);
        jTFStatus.setEditable(true);
        jTFTipo.setEditable(true);
        jTFObs.setEditable(true);
    }

    /**
     * @param args the command line arguments
     */
    //seleciona uma linha na tabela para alterar ou excluir dados 
    private void linhaSelecionada(JTable tabela) {
        if (jTabPesquisa.getSelectedRow() != -1) {
            habilitaDados();
            //jTFIdVeiculo.setText(String.valueOf(veiculo.get(tabela.getSelectedRow()).getIdVeiculo()));
            jTFPlaca.setText(veiculo.get(tabela.getSelectedRow()).getPlaca());
            jTFCor.setText(veiculo.get(tabela.getSelectedRow()).getCor());
            jTFChassi.setText(veiculo.get(tabela.getSelectedRow()).getChassi());
            jTFModelo.setText(veiculo.get(tabela.getSelectedRow()).getModelo());
            jTFMarca.setText(veiculo.get(tabela.getSelectedRow()).getMarca());
            jTFcapacidade.setText(String.valueOf(veiculo.get(tabela.getSelectedRow()).getCapacidade()));
            jTFStatus.setText(veiculo.get(tabela.getSelectedRow()).getStatus());
            jTFTipo.setText(veiculo.get(tabela.getSelectedRow()).getTipo());
            jTFObs.setText(veiculo.get(tabela.getSelectedRow()).getObservacao());
        } else {

            //jTFIdVeiculo.setText("");
            jTFPlaca.setText("");
            jTFCor.setText("");
            jTFChassi.setText("");
            jTFModelo.setText("");
            jTFMarca.setText("");
            jTFcapacidade.setText("");
            jTFStatus.setText("");
            jTFTipo.setText("");
            jTFObs.setText("");
        }
    }

    //verifica se foi deixado algum campo obrigatório em branco
    public boolean verificaDados() {
        if ((!jTFPlaca.getText().equals("")) && (!jTFCor.getText().equals(""))
                && (!jTFChassi.getText().equals("")) && (!jTFModelo.getText().equals("")) && (!jTFMarca.getText().equals(""))
                && (!jTFcapacidade.getText().equals("")) && (!jTFStatus.getText().equals("")) && (!jTFTipo.getText().equals(""))) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Campos obrigatórios em branco!");
            return false;
        }
    }

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */


        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new TelaVeiculo().setVisible(true);
            }
        });
    }
    /*
     * private void gravarVeiculo() { veiculo.setIdVeiculo(new
     * Integer(jTFIdVeiculo.getText())); veiculo.setPlaca(jTFPlaca.getText());
     * veiculo.setCapacidade(new Integer(jTFcapacidade.getText()));
     * daoV.inserir(veiculo); }
     *
     * private void alterarVeiculo() { veiculo.setIdVeiculo(new
     * Integer(jTFIdVeiculo.getText())); veiculo.setPlaca(jTFPlaca.getText());
     * veiculo.setCapacidade(new Integer(jTFcapacidade.getText()));
     * daoV.alterar(veiculo); } private void excluirVeiculo() {
     * veiculo.setIdVeiculo(new Integer(jTFIdVeiculo.getText()));
     * daoV.excluir(veiculo);
}
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbCapacidade;
    private javax.swing.JLabel jLbChassi;
    private javax.swing.JLabel jLbCor;
    private javax.swing.JLabel jLbMarca;
    private javax.swing.JLabel jLbModelo;
    private javax.swing.JLabel jLbObs;
    private javax.swing.JLabel jLbPlaca;
    private javax.swing.JLabel jLbStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFChassi;
    private javax.swing.JTextField jTFCor;
    private javax.swing.JTextField jTFMarca;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFObs;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTextField jTFPlaca;
    private javax.swing.JTextField jTFStatus;
    private javax.swing.JTextField jTFTipo;
    private javax.swing.JTextField jTFcapacidade;
    private javax.swing.JTable jTabPesquisa;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    //mostra a pesquisa na tabela
    private void mostraPesquisa(List<Veiculo> veiculo) {

        while (tmVeiculo.getRowCount() > 0) {
            tmVeiculo.removeRow(0);
        }
        if (veiculo.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum veículo cadastrado!");
        } else {
            String[] linha = new String[]{null, null, null, null, null, null, null, null, null};
            for (int i = 0; i < veiculo.size(); i++) {

                tmVeiculo.addRow(linha);
                //tmVeiculo.setValueAt(veiculo.get(i).getIdVeiculo(), i, 0);
                tmVeiculo.setValueAt(veiculo.get(i).getPlaca(), i, 0);
                tmVeiculo.setValueAt(veiculo.get(i).getCor(), i, 1);
                tmVeiculo.setValueAt(veiculo.get(i).getChassi(), i, 2);
                tmVeiculo.setValueAt(veiculo.get(i).getModelo(), i, 3);
                tmVeiculo.setValueAt(veiculo.get(i).getMarca(), i, 4);
                tmVeiculo.setValueAt(veiculo.get(i).getCapacidade(), i, 5);
                tmVeiculo.setValueAt(veiculo.get(i).getStatus(), i, 6);
                tmVeiculo.setValueAt(veiculo.get(i).getTipo(), i, 7);
                tmVeiculo.setValueAt(veiculo.get(i).getObservacao(), i, 8);

            }
        }
    }

    //altera os dados selecionados na tabela
    private void alterar() throws SQLException {
        if (jTabPesquisa.getSelectedRow() != -1) {
            if (verificaDados()) {
                Veiculo v1 = new Veiculo();
                VeiculoDao dao = new VeiculoDao();
                //v1.setIdVeiculo(Integer.valueOf(jTFIdVeiculo.getText()));
                v1.setPlaca(jTFPlaca.getText());
                v1.setCor(jTFCor.getText());
                v1.setChassi(jTFChassi.getText());
                v1.setModelo(jTFModelo.getText());
                v1.setMarca(jTFMarca.getText());
                v1.setCapacidade(Integer.parseInt(jTFcapacidade.getText()));
                v1.setStatus(jTFStatus.getText());
                v1.setTipo(jTFTipo.getText());
                v1.setObservacao(jTFObs.getText());
                dao.altera(v1);
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
            }
        }
    }
}
