/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.VeiculoDao;
import Negocio.Veiculo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAELA
 */
public class TelaVeiculo extends javax.swing.JFrame {
    
    DefaultTableModel tmVeiculo = new DefaultTableModel(null, new String[]{"IdVeiculo", "Placa", "Capacidade"});
    List<Veiculo> veiculo;
    ListSelectionModel lsmVeiculo;
    /**
     * Creates new form TelaVeiculo
     */
    
    
    public TelaVeiculo() {
        initComponents();
        desabilitaDados();
        //listarVeiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtGravar = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtPesquisar = new javax.swing.JButton();
        jBtNovo = new javax.swing.JButton();
        jTFPesquisar = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLbIdVeiculo = new javax.swing.JLabel();
        jLbPlaca = new javax.swing.JLabel();
        jLbCapacidade = new javax.swing.JLabel();
        jTFIdVeiculo = new javax.swing.JTextField();
        jTFPlaca = new javax.swing.JTextField();
        jTFcapacidade = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabPesquisa = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        jBtGravar.setText("Gravar");
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });

        jBtAlterar.setText("Alterar");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        jBtNovo.setText("Novo");
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtGravar)
                        .addGap(49, 49, 49)
                        .addComponent(jBtAlterar)
                        .addGap(51, 51, 51)
                        .addComponent(jBtExcluir)
                        .addGap(39, 39, 39)
                        .addComponent(jBtNovo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtPesquisar)
                    .addComponent(jTFPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtGravar)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtExcluir)
                    .addComponent(jBtNovo))
                .addGap(22, 22, 22))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(51, 51, 51)));

        jLbIdVeiculo.setText("IdVeículo:");

        jLbPlaca.setText("Placa:");

        jLbCapacidade.setText("Capacidade:");

        jTFcapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcapacidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLbIdVeiculo)
                            .addGap(26, 26, 26))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLbPlaca)
                            .addGap(44, 44, 44)))
                    .addComponent(jLbCapacidade))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFIdVeiculo)
                    .addComponent(jTFPlaca)
                    .addComponent(jTFcapacidade, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbIdVeiculo)
                    .addComponent(jTFIdVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbPlaca)
                    .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbCapacidade)
                    .addComponent(jTFcapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jLbIdVeiculo.getAccessibleContext().setAccessibleName("IdVeículo");

        jTabbedPane2.addTab("Cadastro", jPanel3);

        jTabPesquisa.setModel(tmVeiculo);
        jTabPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmVeiculo = jTabPesquisa.getSelectionModel();
        lsmVeiculo.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    linhaSelecionada(jTabPesquisa);
                }
            }
        });
        jScrollPane1.setViewportView(jTabPesquisa);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Consulta", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFcapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcapacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcapacidadeActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        try {
            // TODO add your handling code here:
            excluir();
            mostraPesquisa(veiculo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão excluir" + ex);
        }
         
    }//GEN-LAST:event_jBtExcluirActionPerformed

    public void excluir() throws SQLException{
        int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir os dados? ", 
                "Confirmação", JOptionPane.YES_NO_OPTION); 
        if(resp == JOptionPane.YES_NO_OPTION){
            VeiculoDao dao = new VeiculoDao();
            dao.exclui(veiculo.get(jTabPesquisa.getSelectedRow()));
            mostraPesquisa(veiculo);
            }         
            
        }
    
    
    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed
        // TODO add your handling code here:
        if (verificaDados()){
            cadastro();
            desabilitaDados();
        }
    }//GEN-LAST:event_jBtGravarActionPerformed

    public void listarVeiculos() throws SQLException{
        VeiculoDao dao = new VeiculoDao();
        veiculo = dao.getLista("%" + jTFPesquisar.getText()+ "%");
        mostraPesquisa(veiculo);
    }
    
    
    public void cadastro(){
        try {
        Veiculo v = new Veiculo();
        
        v.setPlaca(jTFPlaca.getText());
        v.setCapacidade(Integer.parseInt(jTFcapacidade.getText()));
        
            VeiculoDao vd = new VeiculoDao();
            vd.adiciona(v);
        } catch (SQLException ex) {
            Logger.getLogger(TelaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        try {
            // TODO add your handling code here:
            alterar();
            listarVeiculos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no botão alterar" + ex);
        }
        
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
        // TODO add your handling code here:
        habilitaDados();
        jTFIdVeiculo.setText("");
        jTFPlaca.setText("");
        jTFcapacidade.setText("");
    }//GEN-LAST:event_jBtNovoActionPerformed

    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        try {
            // TODO add your handling code here:
            listarVeiculos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed

    public void desabilitaDados(){
        jTFIdVeiculo.setEditable(false);
        jTFPlaca.setEditable(false);
        jTFcapacidade.setEditable(false);
    }
    
    public void habilitaDados(){
        //jTFIdVeiculo.setEditable(false);
        jTFPlaca.setEditable(true);
        jTFcapacidade.setEditable(true);
    }
    /**
     * @param args the command line arguments
     */
    private void linhaSelecionada(JTable tabela){
        if(jTabPesquisa.getSelectedRow() != -1){
            habilitaDados();
            jTFIdVeiculo.setText(String.valueOf(veiculo.get(tabela.getSelectedRow()).getIdVeiculo()));
            jTFPlaca.setText(veiculo.get(tabela.getSelectedRow()).getPlaca());
            jTFcapacidade.setText(String.valueOf(veiculo.get(tabela.getSelectedRow()).getCapacidade()));
        }else{
            jTFIdVeiculo.setText("");
            jTFPlaca.setText("");
            jTFcapacidade.setText("");
        }
    }
    
    public boolean verificaDados(){
        if(!jTFPlaca.getText().equals("")&&!jTFcapacidade.getText().equals("")){
            return true;
        }
        else{
            JOptionPane.showMessageDialog(null,"Campos obrigatórios em branco!");
            return false;
        }
    }
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new TelaVeiculo().setVisible(true);
            }
        });
    }
    /*private void gravarVeiculo() {
            veiculo.setIdVeiculo(new Integer(jTFIdVeiculo.getText()));
            veiculo.setPlaca(jTFPlaca.getText());
            veiculo.setCapacidade(new Integer(jTFcapacidade.getText()));
            daoV.inserir(veiculo);
}

    private void alterarVeiculo() {
            veiculo.setIdVeiculo(new Integer(jTFIdVeiculo.getText()));
            veiculo.setPlaca(jTFPlaca.getText());
            veiculo.setCapacidade(new Integer(jTFcapacidade.getText()));
            daoV.alterar(veiculo);
}
    private void excluirVeiculo() {
            veiculo.setIdVeiculo(new Integer(jTFIdVeiculo.getText()));
            daoV.excluir(veiculo);
}*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JLabel jLbCapacidade;
    private javax.swing.JLabel jLbIdVeiculo;
    private javax.swing.JLabel jLbPlaca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFIdVeiculo;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTextField jTFPlaca;
    private javax.swing.JTextField jTFcapacidade;
    private javax.swing.JTable jTabPesquisa;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void mostraPesquisa(List<Veiculo> veiculo) {
        
        while(tmVeiculo.getRowCount()>0){
            tmVeiculo.removeRow(0);
        }
        if(veiculo.size() == 0){
            JOptionPane.showMessageDialog(null, "Nenhum veículo cadastrado!");
        }
        else{
            String[] linha = new String[]{null, null, null};
            for (int i = 0; i < veiculo.size(); i++) {
                
                tmVeiculo.addRow(linha);
                tmVeiculo.setValueAt(veiculo.get(i).getIdVeiculo(), i, 0);
                tmVeiculo.setValueAt(veiculo.get(i).getPlaca(), i, 1);
                tmVeiculo.setValueAt(veiculo.get(i).getCapacidade(), i, 2);
                
            }
        }
    }

    private void alterar() throws SQLException {
        if(jTabPesquisa.getSelectedRow() != -1){
            if(verificaDados()){
                Veiculo v1 = new Veiculo();
                VeiculoDao dao = new VeiculoDao();
                v1.setIdVeiculo(Integer.valueOf(jTFIdVeiculo.getText()));
                v1.setPlaca(jTFPlaca.getText());
                v1.setCapacidade(Integer.valueOf(jTFcapacidade.getText()));
                dao.altera(v1);
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
            }
        }
    }
}
